# Disable swap
- name: disable swap in fstab (permanent)
  become: yes
  replace:
    path: /etc/fstab
    regexp: '^([^#].*?\sswap\s+swap\s+.*)$'
    replace: '# \1'
- name: disable swap (immediate)
  become: yes
  creates: /var/lib/ansible-kubernetes/disable_swap
  shell: |
    swapoff -a && touch /var/lib/ansible-kubernetes/disable_swap

# Let iptables see bridged traffic
- name: modprob
  become: yes
  modprobe:
    name: br_netfilter
    state: present
- name: k8s sysctl config
  become: yes
  copy:
    src: files/etc/sysctl.d/k8s.conf
    dest: /etc/sysctl.d/k8s.conf
- name: sysctl system
  become: yes
  creates: /var/lib/ansible-kubernetes/sysctl_system
  shell: |
    sysctl --system && touch /var/lib/ansible-kubernetes/sysctl_system

- name: Open port for Kubelet API
  become: yes
  firewalld:
    state: enabled
    port: 10250/tcp
    immediate: yes
    permanent: yes

# Kubernetes v1.18.2 requires conntrack to be installed in root's path
- name: Install conntrack
  become: yes
  yum:
    name: conntrack-tools
    state: present

# Docker
- name: Install Docker
  become: yes
  yum:
    name: docker
    state: present
- name: Start Docker
  become: yes
  service:
    name: docker
    state: started
    enabled: yes

# Kubernetes
- name: Add Kubernetes yum repo
  become: yes
  yum_repository:
    name: kubernetes
    state: present
    description: Kubernetes
    baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
    enabled: yes
    gpgcheck: yes
    repo_gpgcheck: yes
    gpgkey: https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
    exclude: kubelet kubeadm kubectl

- name: Put SELinux in permissive mode, logging actions that would be blocked.
  become: yes
  selinux:
    state: permissive
    policy: targeted

- name: Install kubelet, kubeadm and kubectl
  become: yes
  yum:
    name:
    - kubelet
    - kubeadm
    - kubectl
    state: present
    disable_excludes: kubernetes

- name: Start kubelet service
  become: yes
  service:
    name: kubelet
    state: started
    enabled: yes
