---
apiVersion: v1
kind: Service
metadata:
  namespace: default
  name: caddy
  labels:
    app: caddy
spec:
  ports:
  - name: http
    port: 80
    nodePort: 30080
    protocol: TCP
  selector:
    app: caddy
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: caddy
  labels:
    app: caddy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: caddy
  template:
    metadata:
      labels:
        app: caddy
    spec:
      containers:
      - image: caddy
        name: caddy
        ports:
        - containerPort: 80